- hosts: ubuntu
  
  tasks:

  - debug:
      msg: "{{ ansible_os_family }}"
      
  - name: install the most fresh version of Apache 
    apt:
      name: "{{ package }}"
      state: present
       

  - name: make sure  Apache is started and enabled 
    systemd:
      state: started
      name: "{{ package }}"
      enabled: yes

  - name: Install a list of packages
    apt:
      pkg:
      - wget
      - unzip
    
  - name: Unarchive a file that needs to be downloaded 
    unarchive: 
      src: "{{ template_internet_source }}"
      dest: /tmp/
      remote_src: yes
 
  - name: Copy files    
    copy: 
      src: "{{ template_tmp_source }}"
      dest: /var/www/html
      remote_src: yes  

  
